# CircleCI 2.1 configuration file for https://github.com/zxdavb/geniushub-client
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2.1

jobs:
  build: # runs not using Workflows must have a `build` job as entry point
    docker:  # see: at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.11.6
    working_directory: ~/working_directory
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run:
          command: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - run:
          command: |
            mkdir test-results
            sudo pip install aiohttp

  check_lint:
    docker:
      - image: circleci/python:3.11.6
    steps:
      - checkout
      - run:
          command: |
            sudo pip install nose coverage black
      - run:
          command: |
            mkdir test-results
      - run:
          name: Lint
          command: |
            black --safe --quiet evohomeasync
            black --safe --quiet evohomeasync2
      - run:
          name: Test
          command: |
            pytest --log-cli-level=INFO tests
            pytest --log-cli-level=INFO tests_rf
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: htmlcov
          destination: coverage

  deploy:
    docker:
      - image: circleci/python:3.11.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo pip install -r requirements.txt
            sudo pip install -r requirements-dev.txt
      - run:
          name: Verify git tag vs. package version
          command: python setup.py verify
      - run:
          name: Build the package
          command: |
            sudo python setup.py sdist        # create a source distribution
            sudo python setup.py bdist_wheel  # create a wheel
      - run:
          name: Create .pypirc
          command: |
            echo -e "[distutils]"                                  >> ~/.pypirc
            echo -e "index-servers="                               >> ~/.pypirc
            echo -e "    pypi"                                     >> ~/.pypirc
            echo -e "    test"                                     >> ~/.pypirc
            echo -e ""                                             >> ~/.pypirc
            echo -e "[pypi]"                                       >> ~/.pypirc
            echo -e "repository = https://upload.pypi.org/legacy/" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME"                    >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD"                    >> ~/.pypirc
            echo -e ""                                             >> ~/.pypirc
            echo -e "[test]"                                       >> ~/.pypirc
            echo -e "repository = https://test.pypi.org/legacy/"   >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME"                    >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD"                    >> ~/.pypirc
            echo -e ""                                             >> ~/.pypirc
      - run:
          name: Upload to PyPi
          command: twine upload -r pypi dist/*

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build:
          filters: # required since `check_lint` has tag filters AND requires `build`
            tags:
              only: /.*/
      - check_lint:
          requires:
            - build
          filters: # required since `deploy` has tag filters AND requires `check_lint`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
            - check_lint
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
