#
# https://docs.astral.sh/ruff/integrations/#github-actions

name: Lint with ruff

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: chartboost/ruff-action@v1
